package com.bw.entity;

import java.io.Serializable;

public class Job implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.jobid
     *
     * @mbg.generated Thu Nov 07 09:31:30 CST 2019
     */
    private Integer jobid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.jobname
     *
     * @mbg.generated Thu Nov 07 09:31:30 CST 2019
     */
    private String jobname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table job
     *
     * @mbg.generated Thu Nov 07 09:31:30 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.jobid
     *
     * @return the value of job.jobid
     *
     * @mbg.generated Thu Nov 07 09:31:30 CST 2019
     */
    public Integer getJobid() {
        return jobid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.jobid
     *
     * @param jobid the value for job.jobid
     *
     * @mbg.generated Thu Nov 07 09:31:30 CST 2019
     */
    public void setJobid(Integer jobid) {
        this.jobid = jobid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.jobname
     *
     * @return the value of job.jobname
     *
     * @mbg.generated Thu Nov 07 09:31:30 CST 2019
     */
    public String getJobname() {
        return jobname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.jobname
     *
     * @param jobname the value for job.jobname
     *
     * @mbg.generated Thu Nov 07 09:31:30 CST 2019
     */
    public void setJobname(String jobname) {
        this.jobname = jobname == null ? null : jobname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job
     *
     * @mbg.generated Thu Nov 07 09:31:30 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", jobid=").append(jobid);
        sb.append(", jobname=").append(jobname);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}